# Predicting Heart Disease

 - This project is about predicting heart disease in the patient.
 - The dataset for this project is from the Kaggle.
 - Dataset has a 303 entries with 14 Features

In [1]:
#Importing libraries

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
#Reading Datafile
df  = pd.read_csv("heart.csv")

print('Rows:',df.shape[0])
print('Columns:',df.shape[1])
print('\nFeatures:',df.columns)

Rows: 303
Columns: 14

Features: Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')


In [3]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

## Creating Model

In [4]:
#Independent variables
X = df.drop(['target'],axis=1)
# Dependent Variables
y = df['target']

In [5]:
# Spliting in train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 0)

## Logistic Regression

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
# Model
lr = LogisticRegression()
# Fitting Model
lr.fit(X_train,y_train)
# Predictions
y_pred = lr.predict(X_test)

/home/niraj/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [7]:
# Accuracy Score
score = accuracy_score(y_test, y_pred)
print('Accuracy Score:',score)
# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print('\nconfusion Matrix:\n',cm)
# classification Report
report = classification_report(y_test, y_pred)
print('\nClassification Report:\n',report)

Accuracy Score: 0.8524590163934426

confusion Matrix:
 [[22  5]
 [ 4 30]]

Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.81      0.83        27
           1       0.86      0.88      0.87        34

    accuracy                           0.85        61
   macro avg       0.85      0.85      0.85        61
weighted avg       0.85      0.85      0.85        61



## Support Vector Machine 

In [8]:
from sklearn.svm import SVC
# model
svm = SVC()
# Fitting Model
svm.fit(X_train,y_train)
# Predictions
y_pred  = svm.predict(X_test)

In [9]:
# Accuracy Score
score = accuracy_score(y_test, y_pred)
print('Accuracy Score:',score)
# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print('\nconfusion Matrix:\n',cm)
# classification Report
report = classification_report(y_test, y_pred)
print('\nClassification Report:\n',report)

Accuracy Score: 0.6885245901639344

confusion Matrix:
 [[13 14]
 [ 5 29]]

Classification Report:
               precision    recall  f1-score   support

           0       0.72      0.48      0.58        27
           1       0.67      0.85      0.75        34

    accuracy                           0.69        61
   macro avg       0.70      0.67      0.67        61
weighted avg       0.70      0.69      0.68        61



## Naive Bayes Classification

In [10]:
from sklearn.naive_bayes import GaussianNB
# model
nb = GaussianNB()
# Fitting Model
nb.fit(X_train,y_train)
# Predictions
y_pred  = nb.predict(X_test)

In [11]:
# Accuracy Score
score = accuracy_score(y_test, y_pred)
print('Accuracy Score:',score)
# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print('\nconfusion Matrix:\n',cm)
# classification Report
report = classification_report(y_test, y_pred)
print('\nClassification Report:\n',report)

Accuracy Score: 0.8524590163934426

confusion Matrix:
 [[21  6]
 [ 3 31]]

Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.78      0.82        27
           1       0.84      0.91      0.87        34

    accuracy                           0.85        61
   macro avg       0.86      0.84      0.85        61
weighted avg       0.85      0.85      0.85        61



## Decision Tree Classifier

In [12]:
from sklearn.tree import DecisionTreeClassifier
# Model
dt = DecisionTreeClassifier()
# Fitting Model
dt.fit(X_train,y_train)
# Predictions
y_pred  = dt.predict(X_test)

In [13]:
# Accuracy Score
score = accuracy_score(y_test, y_pred)
print('Accuracy Score:',score)
# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print('\nconfusion Matrix:\n',cm)
# classification Report
report = classification_report(y_test, y_pred)
print('\nClassification Report:\n',report)

Accuracy Score: 0.7868852459016393

confusion Matrix:
 [[21  6]
 [ 7 27]]

Classification Report:
               precision    recall  f1-score   support

           0       0.75      0.78      0.76        27
           1       0.82      0.79      0.81        34

    accuracy                           0.79        61
   macro avg       0.78      0.79      0.78        61
weighted avg       0.79      0.79      0.79        61



## Random Forest Classifier

In [14]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

# Model
rf = RandomForestClassifier()
# Fitting Model
rf.fit(X_train,y_train)
# Predictions
y_pred  = rf.predict(X_test)

In [15]:
# Accuracy Score
score = accuracy_score(y_test, y_pred)
print('Accuracy Score:',score)
# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print('\nconfusion Matrix:\n',cm)
# classification Report
report = classification_report(y_test, y_pred)
print('\nClassification Report:\n',report)

Accuracy Score: 0.8360655737704918

confusion Matrix:
 [[21  6]
 [ 4 30]]

Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.78      0.81        27
           1       0.83      0.88      0.86        34

    accuracy                           0.84        61
   macro avg       0.84      0.83      0.83        61
weighted avg       0.84      0.84      0.84        61



## Optimize Random Forest Classifier

In [16]:
from sklearn.model_selection import RandomizedSearchCV

n_estimators = [int(x) for x in np.linspace(start = 100, stop = 1200, num = 12)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']

criterion = ["gini", "entropy"]
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(5, 30, num = 6)]
# max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10, 15, 100]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 5, 10]


In [17]:
random_grid = {'n_estimators': n_estimators,
               'criterion':criterion,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf}

print(random_grid)

{'n_estimators': [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200], 'criterion': ['gini', 'entropy'], 'max_features': ['auto', 'sqrt'], 'max_depth': [5, 10, 15, 20, 25, 30], 'min_samples_split': [2, 5, 10, 15, 100], 'min_samples_leaf': [1, 2, 5, 10]}


In [18]:
rf = RandomForestClassifier()
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid,scoring='neg_mean_squared_error', n_iter = 10, cv = 5, verbose=2, random_state=42, n_jobs = 1)

In [19]:
rf_random.fit(X_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   2.0s
[CV] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   1.9s
[CV] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   2.0s
[CV] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   1.9s
[CV] END criterion=gini, max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   1.9s
[CV] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, min_samples_split=100, n_estimators=300; total time=   0.6s
[CV] END criterion=entropy, max_depth=30, max_features=auto, min_samples_leaf=2, min_samples_split=100, n_estimators=3

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=1,
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [5, 10, 15, 20, 25, 30],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 5, 10],
                                        'min_samples_split': [2, 5, 10, 15,
                                                              100],
                                        'n_estimators': [100, 200, 300, 400,
                                                         500, 600, 700, 800,
                                                         900, 1000, 1100,
                                                         1200]},
                   random_state=42, scoring='neg_mean_squared_error',
                   verbose=2)

In [20]:
rf_random.best_params_

{'n_estimators': 900,
 'min_samples_split': 5,
 'min_samples_leaf': 5,
 'max_features': 'sqrt',
 'max_depth': 10,
 'criterion': 'gini'}

In [21]:
y_pred  = rf_random.predict(X_test)

In [22]:
# Accuracy Score
score = accuracy_score(y_test, y_pred)
print('Accuracy Score:',score)
# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print('\nconfusion Matrix:\n',cm)
# classification Report
report = classification_report(y_test, y_pred)
print('\nClassification Report:\n',report)

Accuracy Score: 0.8360655737704918

confusion Matrix:
 [[21  6]
 [ 4 30]]

Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.78      0.81        27
           1       0.83      0.88      0.86        34

    accuracy                           0.84        61
   macro avg       0.84      0.83      0.83        61
weighted avg       0.84      0.84      0.84        61

